AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  checkUserPolicies:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/checkUserPolicies.lambda_handler
      Runtime: python3.9
      Policies:
      - IAMReadOnlyAccess
  checkGroupPolicies:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/checkGroupPolicies.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Policies:
      - IAMReadOnlyAccess
  